/**
 * jobs.ch
 * Reverse Engineering of the jobs.ch public API
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './document';


export interface FilterResult { 
    start?: number;
    rows?: number;
    num_pages?: number;
    current_page?: number;
    documents?: Array<Document>;
}

